version: '3.1'

services:


  yoga:
    build:
      context: .
      dockerfile: Dockerfile.yoga.dev
    ports:
      - "4444:4444"
    volumes:
      - ./yoga-server:/usr/src/yoga
    depends_on:
      - mysql
      - prisma
    networks:
      - backend-yoga

  prisma:
    image: prismagraphql/prisma:1.20
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - mysql
    networks:
      - backend-yoga
      - backend-db
    environment:
      # PRISMA_SECRET_FILE: /run/secrets/prisma_secret
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            migrations: true
            port: 3306
            user: root
            password: prisma

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - backend-db

networks:
  backend-yoga:
  backend-db:

volumes:
  mysql: