FROM node:10.13.0

# Copy client package.json and instal client dependencies
WORKDIR /usr/src/app
COPY ./app/package*.json ./
RUN npm install

# Copy client files
COPY ./app/. ./

EXPOSE 7777

CMD ["npm", "run", "dev"]
